service: myPetStore

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  getPet:
    handler: index.handler
    events:
      - http:
          path: /pet
          method: get
  petPet:
    handler: index.handler2
    events:
      - http:
          path: /pet
          method: get
  deletePet:
    handler: index.handler3
    events:
      - http:
          path: /pet
          method: get