service: myPetStore

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  getPet:
    handler: index.getPet
    events:
      - http:
          path: /getPet
          method: get
  createPet:
    handler: index.createPet
    events:
      - http:
          path: /createPet
          method: post
  deletePet:
    handler: index.deletePet
    events:
      - http:
          path: /deletePet
          method: delete